package com.myAgeEducation.cbseClass5.computers;

import com.myAgeEducation.cbseClass5.utils.ImageCodeType;

import java.util.HashMap;
import java.util.Map;

public class FixedComputersQuestionRepository
{
    private static final Map<Integer, String[][]> FIXED_QUESTIONS = new HashMap<>();

    static {
        // Chapter 1:
        FIXED_QUESTIONS.put(1, new String[][]{
                { "Which of these was the first electronic computer?", "ENIAC", "Abacus", "Analytical engine", "UNIVAC", "", null },
                { "Which of these is the smallest and fastest?", "Microprocessors", "Transistors", "Integrated circuits", "Vacuum tubes", "", null },
                { "Which of these is a third generation language?", "All of these", "BASIC", "FORTRAN", "COBOL", "", null },
                { "Debugging a program means:", "Finding and correcting mistakes in it", "Making a flowchart for it", "Writing code for it", "Saving it for future use", null },
                { "The ______ is a calculating aid which uses beads", "Abacus", "ENIAC", "Microprocessors", "Calculators", null },
                { "The first programmable machine was the _______ engine designed by Charles Babbage", "analytical", "ENIAC", "Abacus", "Microprocessors", null },
                { "The _______ is the semiconductor chip used in today's computers.", "microprocessors", "vacuum tubes", "resistors", "transistors", null },
                { "The earliest electronic computers could only understand _______ language.", "machine", "COBOL", "Java", "LOGO", null },
                { "Writing a computer program in a computer language is also known as ________.", "coding", "instructions", "writing", "debugging", null },
                { "What is the full form of LOGO?", "Language of Graphic Oriented", "Language of Graphic Ocean", "Language of Graphic Design", "Language of Google", null },
                { "What is the full form of BASIC?", "Beginners All-purpose Symbolic Instruction Code", "Basic integrated circuit", "Basic and Scientific instruction code", "Beginners and Students Instruction Code", null },
                { "What is the full form of COBOL?", "Common Business Oriented Language", "Catastrophic Business Oriented Language", "Chip Oriented Business Language", "Common Overseas Business Oriented Language", null },
                { "The third generation of computer languages are known as ______ level languages", "high", "low", "top", "bottom", null },
                { "The unit in CPU which performs arithmatic and logical operations is ______", "ALU", "CU", "Cache Memory", "Register", null },
                { "The _____ unit controls processing of data inside a computer, based on the information received from input devices", "Control", "Memory", "Arithmetic and Logic", "", null },
                { "ALU stands for __________________", "Arithmetic and logic unit", "American logic unit", "American language union", "All language union", null },
                { "RAM stands for _________", "Random Access Memory", "Read Only Memory", "Run Away Memory", "Restricted Access Memory", null },
                { "ROM stands for ______", "Read Only Memory", "Random Access Memory", "Run Away Memory", "Restricted Access Memory", null },
                { "When computer is turned off, both data and instructions get lost from ______", "RAM", "ROM", "", "", null },
                { "Which of the following memory is volatile in nature?", "RAM", "ROM", "", "", null },
                { "Which of the following memory is non-volatile in nature?", "ROM", "RAM", "", "", null },
                { "TRUE or FALSE. RAM is non-volatile in nature.", "FALSE", "TRUE", "", "", null },
                { "TRUE or FALSE. ROM is non-volatile in nature.", "TRUE", "FALSE", "", "", null },
                { "This language was named after Blaise Pascal, inventor of Pascaline:", "PASCAL", "FORTRAN", "BASIC", "COBOL", null },
                { "Programs written in ________ can run on machines with any operating system", "Java", "FORTRAN", "BASIC", "LOGO", null },
                { "The computer can only read the data and instructions from it, but cannot make any changes to it. What is it?", "ROM", "RAM", "", "", null },
                { "If you switch OFF the computer, the data present in the _______ is lost.", "RAM", "ROM", "", "", null },
                { "If you switch OFF the computer, the data present in the _______ is not lost.", "ROM", "RAM", "", "", null },
                { "The computers that used valves are referred to as the ___________ generation computers.", "first", "second", "third", "fourth", null },
                { "The computers that used transistors are referred to as the ___________ generation computers.", "second", "first", "third", "fourth", null },
                { "The computers that used Integrated Circuits (ICs) are referred to as the ___________ generation computers.", "third", "first", "second", "fourth", null },
                { "The computers that used Microprocessors are referred to as the ___________ generation computers.", "fourth", "first", "second", "third", null },
                { "ENIAC stands for __________.", "Electronic Numerical Integrator and Computer", "Electronic Numerical Integrator and Calculator", "English Numerical Integrator and Computer", "Electronic Nano Integrator and Computer", null },
                { "UNIVAC stands for __________.", "Universal Automatic Computer", "Universal Automatic Calculator", "Unique, Versatile and Automatic Computer", "Universal Agent Computer", null },
                { "TRUE or FALSE. Valves were used in the first generation of computers", "TRUE", "FALSE", "", "", null },
                { "TRUE or FALSE. Valves were used in the second generation of computers", "FALSE", "TRUE", "", "", null },
                { "TRUE or FALSE. Transistors were used in the second generation of computers", "TRUE", "FALSE", "", "", null },
                { "TRUE or FALSE. Transistors were used in the first generation of computers", "FALSE", "TRUE", "", "", null },
                { "TRUE or FALSE. Integrated Circuits were used in the first generation of computers", "FALSE", "TRUE", "", "", null },
                { "TRUE or FALSE. Integrated Circuits were used in the second generation of computers", "FALSE", "TRUE", "", "", null },
                { "TRUE or FALSE. Integrated Circuits were used in the third generation of computers", "TRUE", "FALSE", "", "", null },
                { "TRUE or FALSE. Integrated Circuits were used in the fourth generation of computers", "FALSE", "TRUE", "", "", null },
                { "TRUE or FALSE. Microprocessors were used in the first generation of computers", "FALSE", "TRUE", "", "", null },
                { "TRUE or FALSE. Microprocessors were used in the second generation of computers", "FALSE", "TRUE", "", "", null },
                { "TRUE or FALSE. Microprocessors were used in the third generation of computers", "FALSE", "TRUE", "", "", null },
                { "TRUE or FALSE. Microprocessors were used in the fourth generation of computers", "TRUE", "FALSE", "", "", null },
                { "TRUE or FALSE. Second generation computers were faster than the First generation of computers", "TRUE", "FALSE", "", "", null },
                { "TRUE or FALSE. First generation computers were faster than the Second generation of computers", "FALSE", "TRUE", "", "", null },
                { "TRUE or FALSE. Second generation computers were faster than the Third generation of computers", "FALSE", "TRUE", "", "", null },
                { "TRUE or FALSE. Third generation computers were faster than the Second generation of computers", "TRUE", "FALSE", "", "", null },
                { "TRUE or FALSE. The computers that we use today are First Generation of computers", "FALSE", "TRUE", "", "", null },
                { "TRUE or FALSE. The computers that we use today are Second Generation of computers", "FALSE", "TRUE", "", "", null },
                { "TRUE or FALSE. The computers that we use today are Third Generation of computers", "FALSE", "TRUE", "", "", null },
                { "TRUE or FALSE. The computers that we use today are Fourth Generation of computers", "TRUE", "FALSE", "", "", null },
                { "TRUE or FALSE. The computers that we use today are Fifth Generation of computers", "FALSE", "TRUE", "", "", null },
                { "Which one of the following computers is smallest in size?", "Fourth generation of computers", "First generation of computers", "Second generation of computers", "Third generation of computers", null },
                { "Which one of the following computers is biggest in size?", "First generation of computers", "Second generation of computers", "Third generation of computers", "Fourth generation of computers", null },
                { "Which one of the following computers is the fastest?", "Fourth generation of computers", "First generation of computers", "Second generation of computers", "Third generation of computers", null },
                { "Which one of the following computers is the slowest?", "First generation of computers", "Second generation of computers", "Third generation of computers", "Fourth generation of computers", null },
                { "TRUE or FALSE. An Integrated Circuit (IC) consists of several transistors and other electronic components on a single silicon chip", "TRUE", "FALSE", "", "", null },
                { "Which of the following electronic component consists of thousands of transistors and other electronic components on a single silicon chip?", "Microprocessor", "Transistor", "Vacuum tube", "Integrated Circuit", null },
                { "IBM360 was a __________ generation computer.", "Third", "First", "Second", "Fourth", null },
                { "IBM370 was a __________ generation computer.", "Third", "First", "Second", "Fourth", null },
                { "TRUE or FALSE. IBM370 was a fourth generation computer.", "FALSE", "TRUE", "", "", null },
                { "The electronic component shown in the picture is a _________.", "Vacuum tube (valve)", "Microprocessor", "Transistor", "Integrated Circuit", ImageCodeType.RESOURCE_IMAGE + ";computers_1065" },
                { "The electronic component shown in the picture is a _________.", "Microprocessor", "Vacuum tube (valve)", "Transistor", "Integrated Circuit", ImageCodeType.RESOURCE_IMAGE + ";computers_1066" },
                { "The electronic component shown in the picture is a _________.", "Transistor", "Vacuum tube (valve)", "Microprocessor", "Integrated Circuit", ImageCodeType.RESOURCE_IMAGE + ";computers_1067" },
                { "The electronic component shown in the picture is a _________.", "Transistor", "Vacuum tube (valve)", "Microprocessor", "Integrated Circuit", ImageCodeType.RESOURCE_IMAGE + ";computers_1068" },
                {/*1069*/ "The electronic component shown in the picture is a/an _________.", "Integrated Circuit", "Vacuum tube (valve)", "Microprocessor", "Transistor", ImageCodeType.RESOURCE_IMAGE + ";computers_1069" },
                { "TRUE or FALSE. You will find Super Computers in homes and schools.", "FALSE", "TRUE", "", "", null },
                { "TRUE or FALSE. You will find Personal Computers in homes and schools.", "TRUE", "FALSE", "", "", null },
                { "TRUE or FALSE. Fourth Generation computers are as big as First Generation computers.", "FALSE", "TRUE", "", "", null },
                { "Which company built the first microprocessor?", "Intel", "AMD", "Qualcomm", "Samsung", null },
                { "The speed of a computer is measured by the number of instructions the microprocessor can carry out in one second. This is measured in MIPS. MIPS stands for _______", "Millions Instructions Per Second", "Millions Interchange Per Second", "Minimum Instructions Per Second", "Maximum Instructions Per Second", null },
                { "TRUE or FALSE. Intel built the first microprocessor", "TRUE", "FALSE", "", "", null },
                { "TRUE or FALSE. Samsung built the first microprocessor", "FALSE", "TRUE", "", "", null },
                { /*1077*/ "The picture shown below is probably the first real counting and calculating aid. It is called _______", "Abacus", "Napier's bones", "Analytical engine", "Pascaline", ImageCodeType.RESOURCE_IMAGE + ";computers_1077" },
                { /*1078*/ "The picture shown below is a set of rods made by John Napier. It was used for multiplying numbers. It is called _______", "Napier's bones", "Abacus", "Analytical engine", "Pascaline", ImageCodeType.RESOURCE_IMAGE + ";computers_1078" },
                { "Blaise Pascal made an adding machine using gears (toothed wheels). This machine was called ________. This was the first real mechanical calculating machine.", "Pascaline", "Abacus", "Napier's bones", "Analytical engine", null },
                { "The first real mechanical calculating machine was ________.", "Pascaline", "Abacus", "Napier's bones", "Analytical engine", null },
                { "TRUE or FALSE. ENIAC, the first electronic computer, was the fastest computer ever made.", "FALSE", "TRUE", "", "", null },
                { "TRUE or FALSE. Second Generation computers were the fastest computers.", "FALSE", "TRUE", "", "", null },
                { "PARAM Yuva II, EKA and SAGA-220 are some super computers made in ________.", "India", "USA", "Japan", "China", null },
                { "TRUE or FALSE. Intel microprocessors were used in the Third Generation of computers.", "FALSE", "TRUE", "", "", null },
                { "TRUE or FALSE. Intel microprocessors were used in the First Generation of computers.", "FALSE", "TRUE", "", "", null },
                { "People who specializes in programming a computer are called _______ _________.", "computer programmers", "computer operators", "", "", null },
                { "The steps needed to make a computer program are:", "Planning --> Coding --> Testing and Debugging", "Coding -->  Testing and Debugging --> Planning", "Coding -->  Planning --> Testing and Debugging", "Planning --> Testing and Debugging --> Coding", null },
                { "Which of the following is the main difference between RAM and ROM", "RAM is volatile and ROM is non-volatile", "RAM is non-volatile and ROM is volatile", "RAM is primary and ROM is secondary memory", "RAM is secondary and ROM is primary memory", null },
                { "What is Artificial Intelligence?", "The ability of computers to make decisions like humans based on the vast amount of information stored in them", "The ability of computers to run computer programs like games", "The ability of computers to run 4K videos with spectecular scenes and sounds", "The ability of computers to play Dolbi Digital sound tracks", null },
                { "What is an Integrated Circuit (IC)?", "An IC is a semiconductor device consisting of several transistors and other electronic components on a single chip", "An IC is like a vacuum tubes used in the first generation of computers", "An IC is another name for transistors", "An IC is the motherboard of computers", null },
                { "The CPU is the brain of the computer. It is made up of three main units: Memory unit, Artithmetic and logic unit and _________", "Control Unit", "RAM unit", "ROM unit", "AL unit", null },
                { "Machine language is known as the first generation of computer languages. It is made up of only two numbers: ________", "0 and 1", "1 and -1", "10 and 100", "6 and 7", null },
                { "Computers with Artificial Intelligence are termed as the _______ generation computers", "fifth", "first", "second", "fourth", null },
                { "_______ stores data and instructions permanently", "ROM", "RAM", "", "", null },
                { "_______ stores data and instructions temporarily", "RAM", "ROM", "", "", null },
                { "The _____ unit controls all the operations of a computer, based on the information received from input devices", "Control", "Memory", "Arithmetic and Logic", "", null },
                { "The _____ unit of CPU is responsible for all the mathematical calculations", "Arithmetic and Logic", "Control", "Memory", "", null },
                { "The _____ unit of CPU is responsible for doing all the logical functions such as: Is 10 is smaller than 20?", "Arithmetic and Logic", "Control", "Memory", "", null },
                { "Which of the following is not a programming language?", "MS Paint", "LOGO", "Java", "PASCAL", null },
                { "Which of the following is a programming language?", "Java", "MS Word", "MS Paint", "MS PowerPoint", null },
                { "TRUE or FALSE. IBM360 was a first generation computer", "FALSE", "TRUE", "", "", null },
                { "Which one of the following is the invention of Blaise Pascal?", "Pascaline", "Microprocessor", "Vacuum tubes", "Analytical engine", null },
                { "__________ is used as a programming language in first generation computers?", "Machine Language", "FORTRAN", "COBOL", "BASIC", null },
                { "FORTRAN stands for __________.", "Formula Translation", "For Translation", "Format Transformation", "Fork Transformation", null },
                { "PARAM Yuva II, EKA and SAGA-220 are some ________ computers.", "super", "personal", "boring", "gaming", null },
                { "Which one of the following is the invention of John Napier. It was used for multiplying numbers.", "Napier's bones", "Abacus", "Analytical engine", "Pascaline", null },
                { "Which one of the following is the invention of Charles Babbage?", "Analytical engine", "Abacus", "Napier's bones", "Pascaline", null },
                { "Which one of the following is the invention of John Presper Eckert and John William Mauchly?", "ENIAC", "Abacus", "Analytical engine", "Pascaline", null },
                { "Which of the following is a characteristics of First Generation of computers?", "First generation of computers were made using valves", "First generation of computers were made using microprocessors", "First generation of computers were faster than second generation of computers", "First generation of computers were smaller than fourth generation of computers", null },
                { "Which of the following is NOT a characteristics of Fourth Generation of computers?", "Fourth generation of computers are bigger than third generation of computers", "Fourth generation of computers are faster than it previous generations", "Fourth generation of computers are made using microprocessors", "Fourth generation of computers are smaller than second generation of computers", null },
                { "TRUE or FALSE. It is very difficult to write a program in machine language", "TRUE", "FALSE", "", "", null },
                { "TRUE or FALSE. It is easy to write a program in a high level language compared to machine language", "TRUE", "FALSE", "", "", null },
                { "Integrated Circuits (ICs) are made of ________ material", "silicon", "plastic", "rubber", "platinum", null },
                { "What is MIPS?", "Millions Instruction Per Second - the number of instructions a microprocessor can carry out in one second", "Maximum Instruction Per Second - the maximum instructions a microprocessor can carry out in one second", "", "", null },
                { "What is the full form of C-DAC?", "Center for Development of Advanced Computing", "Common Development Activities in Computers", "", "", null },
                { "Computer memory is classified into primary memory and ________ memory", "secondary", "volatile", "", "", null },
                { "Which of the following is a secondary storage device?", "Hard disk", "RAM", "ROM", "Mouse", null },
                { "Which of the following is NOT a secondary storage device?", "RAM", "Hard disk", "Pen drives", "DVDs", null },
                { "_______ stores programs that instruct the computer how to control its various parts and how to process data.", "ROM", "RAM", "", "", null },
                { "TRUE or FALSE. High-level languages such as BASIC, FORTRAN and COBOL are fifth generation computer languages.", "FALSE", "TRUE", "", "", null },
                { "The computer size was very large in ____________", "First generation", "Second generation", "Third generation", "Fourth generation", null },
                {/*1122*/ "Chief component of first generation computer was ____________", "Vacuum Tubes and Valves", "Transistors", "Integrated Circuits", "Microprocessors", null },
        });

        // Chapter 2:
        FIXED_QUESTIONS.put(2, new String[][]{
                { "Which of these is not present in the Start menu?", "Recycle Bin", "Computer", "Documents", "Control Panel", null },
                { "If you want to get information about a file, which of the following menu items will you choose from the right-click menu?", "Properties", "Open", "Cut", "Copy", null },
                { "You can access the search facility from the:", "Start button", "Right-click menu", "Computer icon", "Document icon", null },
                { "TRUE or FALSE. I do not remember in which folder I saved the file 'letter'. I now have to open each folder to search for it", "FALSE", "TRUE", "", "", null },
                { "TRUE or FALSE. Once a file is sent to the Recycle Bin it gets deleted from the computer", "FALSE", "TRUE", "", "", null },
                { "TRUE or FALSE. You cannot open a new file on the computer; you can only work on the existing files.", "FALSE", "TRUE", "", "", null },
                { "TRUE or FALSE. To search for a file on the computer you must type its full name.", "FALSE", "TRUE", "", "", null },
                { "Which of these appears on the screen if the computer remains idle for sometime?", "Screen Saver", "Wallpaper", "Documents", "Desktop", null },
                { "Which option on the drop-down menu will you choose if you want to move a file from one folder to another?", "Cut and Paste", "Copy and Paste", "Rename", "New", null },
                { "Which one of the following statements is FALSE?", "Copy and Paste command is used to move a file", "We can rename a file after we create it", "We can have a folder inside a folder", "We can delete a folder", null },
                { "TRUE or FALSE. A folder can have other folders stored in it.", "TRUE", "FALSE", "", "", null },
                { "TRUE or FALSE. Once you have created and named a folder, you cannot change its name", "FALSE", "TRUE", "", "", null },
                { "TRUE or FALSE. If you have your own picture saved on your computer you can make it the wallpaper", "TRUE", "FALSE", "", "", null },
                { "TRUE or FALSE. Disk cleanup checks the hard disk for errors.", "FALSE", "TRUE", "", "", null },
                { "____ is a word processing program in the Accessories folder that can be used to write letters and insert pictures in a document", "Wordpad", "Notepad", "Calculator", "Scan disk", null },
                { "I am the process by which the operating system loads in the memory of a computer", "booting", "restarting", "shutdown", "start", null },
                { "Windows 7 is an operating System developed by __________", "Microsoft", "Google", "Apple", "TCS", null },
                { "TRUE or FALSE. Windows XP is the latest version of Windows.", "FALSE", "TRUE", "", "", null },
                { "I am a rectangular panel at the bottom of the desktop. I am _______", "Taskbar", "Icons", "Notification area", "Start button", null },
                { "We stand for different programs, files, and folders on the desktop. We are _____", "Icons", "Wallpaper", "Screensaver", "Taskbar", null },
                { "______________________ controls and manages the operation of a computer.", "Operating System", "Application software", "Utility Software", "", null },
                { "The pointer shape changes to ______ when we resize the window.", "Double headed arrow", "Normal", "Busy", "Four headed arrow", null },
                { "The _________ button gives quick access to documents, Windows application and help menu etc.", "Start", "Control Panel", "Task bar", "All", null },
                { "TRUE or FALSE. Linux is one of the most popular operating system software", "FALSE", "TRUE", "", "", null },
                { "I am a button that opens up the Start menu and from where you can shut down the computer", "Start button", "Taskbar", "Documents", "My Computer", null },
                { "TRUE or FALSE. The mouse pointer is a small arrow on the computer screen.", "TRUE", "FALSE", "", "", null },
                { "TRUE or FALSE. Icon is a long colourful bar located at the bottom of the desktop.", "FALSE", "TRUE", "", "", null },
                { "TRUE or FALSE. When you delete a file from a hard disk, the deleted file is stored in the Recycle Bin where you can recover it until you empty the Recycle Bin.", "TRUE", "FALSE", "", "", null },
                { "When sizing a window", "Mouse pointer change into a two-headed arrow", "Mouse pointer change into a three-headed arrow", "Mouse pointer has one-headed arrow", "", null },
                { /*2102*/ "The logo in the picture represents?", "None of these", "Windows 98", "Windows 95", "Unix", ImageCodeType.RESOURCE_IMAGE + ";computers_2102" },
                { "Name the icon shown in the picture", "Recycle Bin", "My Computer", "Start button", "My Network", ImageCodeType.RESOURCE_IMAGE + ";computers_2103" },
                {"A set of programs that manages the computer hardware is called the _______", "Operating System", "Application software", "Utility Software", "MS Excel", null },
                {"Which of the following is an operating system software?", "Android", "MS Word", "MS Paint", "MSW LOGO", null},
                {/*2202*/ "Name the image shown in the picture", "Start button", "Recycle Bin", "My Network" ,"Windows 7", ImageCodeType.RESOURCE_IMAGE + ";computers_2202" },
                {/*2203*/ "Which of the following statement is FALSE for a newer version of a software?", "Newer version of the software is entirely different from the older versions", "The errors found in the earlier versions are corrected in the newer versions", "New features may be added in the newer versions" ,"", null },
                {"TRUE or FALSE. All computers have the same number of icons on its desktop.", "FALSE", "TRUE", "", "", null },
                {"Windows Operating System was developed by a software company called _________ Corporation.", "Microsoft", "Google", "Apple", "TCS", null},
                {"_________ is the earliest version of Windows", "Windows 3.1", "Windows 98", "Windows XP", "Windows 7"},
                {"TRUE or FALSE. Windows XP is the latest version of Windows.", "FALSE", "TRUE", "", ""},
                {"TRUE or FALSE. Windows NT (New Technology) is the latest version of Windows.", "FALSE", "TRUE", "", ""},
                {"TRUE or FALSE. Windows 7 is the latest version of Windows.", "FALSE", "TRUE", "", ""},
                {"TRUE or FALSE. Windows 8 is the latest version of Windows.", "FALSE", "TRUE", "", ""},
                {"TRUE or FALSE. Windows 10 is the latest version of Windows.", "FALSE", "TRUE", "", ""},
                {"There are 2 procedures given in the box below to create a file. Which one is the correct procedure?", "Procedure 2", "Procedure 1", "", "", "Procedure 1:\n===========\n1. Open the folder or drive where you want to create a new folder.\n2. Right-click in the blank portion within the folder making sure no file is selected at that time.\n3. Choose 'New' from the drop-down menu and again select 'Folder' from the next drop-down menu.\n4. Now a new folder icon will appear in the folder or drive. Type the name of the folder.\n\nProcedure 2:\n===========\n1. Open the folder or drive where you want to create a new file.\n2. Right-click in the blank portion within the folder making sure no file is selected at that time.\n3. Choose 'New' from the drop-down menu and again select type of the file you want to create from the next drop-down menu.\n4. Now a new file icon will appear in the folder or drive. Type the name of the file.", null},
                {"TRUE or FALSE. Windows, and application software such as MS Office, have only one version.", "FALSE", "TRUE", "", "", null},
                {"In MS-Office 2000, MS-Office-2013, the numbers 2000 and 2013 refers to its ________ numbers", "version", "year", "features", ""},
                {"To delete a file in Windows, two steps are needed. What are the two steps?", "1. Select the file and 2. Press the DELETE key on the keyboard", "1. Select the file and 2. Press the ENTER key on the keyboard", "1. Select the file and 2. Right-click the file", "1. Select the file and 2. Press the HOME key on the keyboard"},
                {"TRUE or FALSE. Windows, and application software such as MS Office, have many versions.", "TRUE", "FALSE", "", ""},
        });

        // Chapter 3:
        FIXED_QUESTIONS.put(3, new String[][]{
                { "If you want to change the page margins in your document which tab will you click on?", "Page Layout", "Home", "Insert", "Review", null },
                { "To print your document which tab will you go to?", "None of these", "Home", "Insert", "Page Layout", null },
                { "To add header to a document you can use the?", "Insert tab", "Home tag", "Office button", "Either Insert tab or Office button", null },
                { "In the landscape orientation:", "Width > length", "Width = length", "Width < length", "", null },
                { "Which of these shapes are available in the Shapes menu?", "All of these", "Stars", "Arrows", "Banners", null },
                { "To delete a paragraph, select the paragraph and press the _______ key", "DELETE", "CTRL", "SHIFT", "HOME", null },
                { "When you cut a portion of text, it goes to the ________", "Clipboard", "Recycle Bin", "My Computer", "Hard disk", null },
                { "To get to the Page Number dialog box, you will go to the ______ tab, Header and Footer group", "Insert", "Home", "Page Layout", "View", null },
                { "To get to the Page Number dialog box, you will go to the Insert tab, __________ group", "Header and Footer", "Home", "Page Layout", "View", null },
                { "To change margins on a page you have to open the ________ dialog box by going to the Page Layout tab and clicking on Custom Margins", "Page Setup", "Page Layout", "Custom Margins", "Home", null },
                { "To change margins on a page you have to open the Page Setup dialog box by going to the Page Layout tab and clicking on Custom ________", "Margins", "Setup", "Layout", "Home", null },
                { "To change margins on a page you have to open the Page Setup dialog box by going to the _________ tab and clicking on Custom Margins", "Page Layout", "Page Setup", "Custom Margins", "Home", null },
                { "A book cover consits of three parts: the back cover, the ______ and the front cover", "spine", "portrait", "landscape", "orientation", null },
                { "A book cover is printed on the ___________ orientation", "portrait", "landscape", "", "", null },
                { "If you want to rotate a portion of text, it must be entered as an ________", "object", "text", "oval", "circle", null },
                { "Which command will you use to move text from one place to another in your document?", "Cut-paste", "Cut-copy", "Copy-paste", "Cut-move", null },
                { "The highlight option is present in the:", "Home tab, Font group", "Home tab, Paragraph group", "Home tab, Clipboard group", "Insert tab, Highlight group", null },
                { "Which icon will you press to insert into a Word document, a picture saved in a folder in your computer?", "Insert tab -> Picture", "Home tab -> Clip Art", "Insert tab -> Clip Art", "Home tab -> Picture", null },
                { "You have selected some text. To delete it, which of these will you press?", "Delete key", "ESC key", "Enter key", "Backspace key", null },
                { "The ______ command is used to cancel the previous command", "UNDO", "REDO", "DONT DO", "ALWAYS DO", null },
                { "To remove boldface on a word, you select it and press ______ key", "Ctrl + B", "Ctrl + C", "Ctrl + Y", "Ctrl + X", null },
                { "To copy a portion of text, you will select it and then use the commands _____ and paste", "copy", "delete", "cut", "paste", null },
                { "After creating a border you want to choose the colour inside the border. You will use the Home tab -> Paragraph group -> Borders button -> ______ tab", "Shading", "Colour", "Page Border", "Borders", null },
                { "What does red wavy line below a word in MS Word indicate?", "spelling mistake", "grammer mistake", "", "", null },
                { /*3025*/ "Which of the following picture in the box below indicate portrait orientation?", "Picture A", "Picture B", "", "", ImageCodeType.RESOURCE_IMAGE + ";computers_3025_26_27_28_29_30" },
                { "Which of the following picture in the box below indicate landscape orientation?", "Picture B", "Picture A", "", "", ImageCodeType.RESOURCE_IMAGE + ";computers_3025_26_27_28_29_30" },
                { "TRUE or FALSE. Picture A in the given picture below indicate Portrait orientation.", "TRUE", "FALSE", "", "", ImageCodeType.RESOURCE_IMAGE + ";computers_3025_26_27_28_29_30" },
                { "TRUE or FALSE. Picture B in the given picture below indicate Portrait orientation.", "FALSE", "TRUE", "", "", ImageCodeType.RESOURCE_IMAGE + ";computers_3025_26_27_28_29_30" },
                { "TRUE or FALSE. Picture A in the given picture below indicate Landscape orientation.", "FALSE", "TRUE", "", "", ImageCodeType.RESOURCE_IMAGE + ";computers_3025_26_27_28_29_30" },
                { "TRUE or FALSE. Picture B in the given picture below indicate Landscape orientation.", "TRUE", "FALSE", "", "", ImageCodeType.RESOURCE_IMAGE + ";computers_3025_26_27_28_29_30" },
                { "The 2 types of page orientations in MS-Word are:", "Portrait and Landscape", "Horizontal and Vertical", "A3 and A4", "Bold and Italics", null },
                { "Settings which are fixed from before are called _______", "default settings", "vertical settings", "bold settings", "computer settings", null },
                { "If you give 'my work' as a header in a document, will it appear only on the first page or on all pages of the document", "on all the pages", "only on the first page", "", "", null },
                { "In MS-Word, in which of the following tab has the 'Bullets' option?", "Home", "Insert", "Design", "View", null },
                { "In MS-Word, in which of the following group under the HOME tab has the 'Bullets' option?", "Paragraph", "Clipboard", "Font", "Styles", null },
                { /*3036*/ "In the given picture, there are 2 lists, A and B. Which of the 2 list is 'Bulleted list'?", "List A", "List B", "Both A and B", "", ImageCodeType.RESOURCE_IMAGE + ";computers_3036_37" },
                { /*3037*/ "In the given picture, there are 2 lists, A and B. Which of the 2 list is 'Numbered list'?", "List B", "List A", "Both A and B", "", ImageCodeType.RESOURCE_IMAGE + ";computers_3036_37" },
                { /*3038*/ "The picture below shows a bulleted list of items. In most cases, a bullet is a small dot. In MS-Word, is it possible to have other symbols as bullet?", "Yes", "No", "", "", ImageCodeType.RESOURCE_IMAGE + ";computers_3038" },
        });

        // Chapter 4:
        FIXED_QUESTIONS.put(4, new String[][]{
                //chapter 4
                { "In MS-Word, a table can be created from which of the following tabs?", "Insert", "Home", "Page Layout", "Office button", null },
                { "You want to merge two cells. In MS-Word, on which tab is the option for merging cells found?", "Table Tools -> Layout", "Insert", "Page Layout", "Table Tools -> Design", null },
                { "In MS-Word, Graphics can be added in a table from the:", "Insert", "Page Layout", "Table Tools -> Layout", "Table Tools -> Design", null },
                { "Arrangement of information in rows and columns is called a ________", "table", "cell", "column", "row", null },
                { "The box where a row and a column meet is called a ________", "cell", "table", "column", "row", null },
                { "The vertical series of cells in a table is called a ________", "column", "table", "cell", "row", null },
                { "The horizontal series of cells in a table is called a ________", "row", "table", "cell", "column", null },
                { /*4008*/ "How many rows are there in the table given in the picture?", "6", "4", "5", "3", ImageCodeType.RESOURCE_IMAGE + ";computers_4008_09_10_11_12_13" },
                { /*4009*/ "How many columns are there in the table given in the picture?", "4", "6", "5", "3", ImageCodeType.RESOURCE_IMAGE + ";computers_4008_09_10_11_12_13" },
                { /*4010*/ "How many cells are there in the table given in the picture?", "24", "6", "4", "5", ImageCodeType.RESOURCE_IMAGE + ";computers_4008_09_10_11_12_13" },
                { /*4011*/ "How many cells are there in the first row of the table given in the picture?", "4", "6", "5", "24", ImageCodeType.RESOURCE_IMAGE + ";computers_4008_09_10_11_12_13" },
                { /*4012*/ "How many cells are there in the first column of the table given in the picture?", "6", "4", "5", "24", ImageCodeType.RESOURCE_IMAGE + ";computers_4008_09_10_11_12_13" },
                { /*4013*/ "TRUE or FALSE. The number of rows is equal to the number of columns in the table given in the picture?", "FALSE", "TRUE", "", "", ImageCodeType.RESOURCE_IMAGE + ";computers_4008_09_10_11_12_13" },
                { "TRUE or FALSE. You can only enter text in a table, not graphics.", "FALSE", "TRUE", "", "", null },
                { "In MS-Word, what is the default alignment of text in a table?", "top-left", "bottom-left", "bottom-right", "top-right", null },
                { "In MS-Word, what options are there for vertical alignment of text in a cell of a table?", "top, center or bottom", "left, center or right", "", "", null },
                { "In MS-Word, what options are there for horizontal alignment of text in a cell of a table?", "left, center or right", "top, center or bottom", "", "", null },
                { "In MS-Word, is it possible to add a new row to a table?", "Yes", "No", "", "", null },
                { "In MS-Word, can we delete a row from a table?", "Yes", "No", "", "", null },
        });

        // Chapter 5:
        FIXED_QUESTIONS.put(5, new String[][]{
                //chapter 5
                { "Which of these is not a part of the MS Office package?", "Paint", "Word", "Excel", "PowerPoint", null },
                { "The title slide consists of which of these:", "Both Title and Subtitle", "Title", "Subtitle", "Clip Art", null },
                { "You can view your slides in which of the following views?", "All of these", "Slide Sorter", "Notes Pages", "Slide Show", null },
                { "To give a shaded background to a slide which of the following Fill option will you choose?", "Gradient fill", "Solid fill", "Picture or Texture fill", "All of these", null },
                { "To give background color to your slide you have to go to ______ in the Design tab.", "Background Styles", "Solid fill", "scanner", "four", null },
                { "To give a single colour to the background of your slide, you will select _______ in the Format Background dialog box.", "Solid fill", "Background Styles", "scanner", "four", null },
                { "To insert your photograph in a slide, you will need a __________, which will convert the photograph into a file, and store it on the hard disk.", "scanner", "Background Styles", "Solid fill", "four", null },
                { "In PowerPoint, you can view your slides in _______ different ways.", "four", "Background Styles", "Solid fill", "scanner", null },
                { "Which of these tabs present in MS Word is not present in MS PowerPoint?", "Page layout", "Home", "Insert", "View", null },
                { "Which icon will you click on to insert into a presentation, a picture saved in a folder in your computer?", "Insert tab -> Picture", "Home tab -> Picture", "Insert tab -> Clip Art", "Home tab -> Clip Art", null },
                { "How many place holders are there in the standard Title Slide?", "2", "1", "3", "4", null },
                { "How can you see a presentation as a slide show?", "Slide show -> From Beginning", "Home -> Slide Show", "Insert -> From Beginning", "View -> From Beginning", null },
                { "To start MS PowerPoint, Click Start button -> _______ -> Microsoft Office 2007 -> Microsoft PowerPoint 2007", "All Programs", "Accessories", "Notepad", "Wordpad", null },
                { "The ________ _______ dialog box shows the different slide layouts", "Office Theme", "Save As", "Save like", "Open file", null },
                { "Normally the layout chosen for the first slide of a presentation is the ______ layout", "Title Slide", "Title and Content", "Section Header", "Content with Caption", null },
                { "To save your presentation for the first time select _______ from the Office button menu", "Save As", "Open As", "Save", "Print", null },
                { "To stop a running slide show, press the _______ key", "Esc", "Ctrl", "Space bar", "Shift", null },
        });

        // Chapter 6:
        FIXED_QUESTIONS.put(6, new String[][]{
                { "Which of the following is a spreadsheet?", "Your report card", "A letter from your teacher to your parent", "", "", null },
                { "The cell A1 is:", "In column A, row 1", "In row A, column 1", "", "", null },
                { "Which of the following is the correct formula to be entered in an Excel sheet for adding the contents of two cells A1 and B1?", "= A1 + B1", "A1 + B1", "A1 add B1", "", null },
                { "The sign for multiplication in a spreadsheet is:", "*", "X", "x", "/", null },
                { "The chart group is present in which of the following tabs?", "Insert", "Home", "Page Layout", "View", null },
                { "The selected cell in a spreadsheet is called the ______ cell.", "active", "passive", "composite", "hyper", null },
                { "For the menu with Save as option, you have to press the ______ button.", "Office", "Home", "Insert", "View", null },
                { "To do a calculation in a spreadsheet you have to enter a ________.", "formula", "picture", "sound", "video", null },
                { "In Excel, a chart consisting of vertical bars is called ________ chart.", "Column", "Line", "Pie", "Area", null },
                { "The first electronic spreadsheet software was ________.", "VisiCalc", "Lotus 1-2-3", "MS Excel", "MS Word", null },
                { "There are _______ columns in MS Excel 2007 spreadsheet.", "256", "212", "512", "200", null },
                { "In MS-Excel, spreadsheets are also known as _______.", "worksheets", "pages", "Power Point", "images", null },
                { "What is the name of the first column in MS-Excel?", "A", "1", "Column-1", "Line-1", null },
                { "A row and a column meet in a small rectangular area called ______", "cell", "box", "rectangle", "triangle", null },
                { /*6015*/ "Which cell is the active cell in the Excel spreadsheet given in the picture?", "B4", "4B", "ABCD", "1234", ImageCodeType.RESOURCE_IMAGE + ";computers_6015" },
        });

        // Chapter 7:
        FIXED_QUESTIONS.put(7, new String[][]{
                { "Multimedia uses which of the following?", "All of these", "Text and pictures", "Sound and animation", "Videos", null },
                { "What is the name of the media player that comes with Windows 7?", "Windows Media Player", "Word Media Player", "PowerPoint media player", "Windows movie maker", null },
                { "Multimedia designing software can be used to design:", "All of these", "Cars", "Aeroplanes", "Buildings", null },
                { "The term ______ refers to multiple forms of communication media", "multimedia", "software", "hardware", "telephone", null },
                { "_______ are multimedia software that create a realistic environment inside a classroom", "Simulators", "Word processors", "Spreadsheets", "Windows Movie Maker", null },
                { "Multimedia helps doctors to see 3D view of internal _______ of the body", "organs", "diseases", "", "", null },
                { "The working of machine can be best explained with the help of _______", "animation", "image", "", "", null },
                { "You should double-click the file called Setup to _______ the program on your computer.", "install", "delete", "create", "watch", null },
                { "To start Windows Media Player, click Start --> ____________ --> Windows Media Player.", "All Programs", "Accessories", "System tasks", "Windows Movie Maker", null },
        });

        // Chapter 8:
        FIXED_QUESTIONS.put(8, new String[][]{
                { "Which of these commands clears the screen and returns the turtle to the HOME position?", "Both CLEARSCREEN and CS command", "CLEARSCREEN", "CS", "CLEAN", null },
                { "1 turtle turn is equal to:?", "1 degree", "10 degree", "30 degree", "90 degree", null },
                { "The number for red colour in LOGO is 4. To colour the background which of the following commands will you give?", "SETSC 4", "SETPC 4", "SETFC 4", "SETBC 4", null },
                { "The ________ command is given to display all procedures currently in the computer memory", "POTS", "SAVE", "LOAD", "EDIT", null },
                { "The ________ command clears the screen and leaves the turtle in its current position", "CLEAN", "CLEARSCREEN", "CS", "CLEARTEXT", null },
                { "The words used as LOGO commands are called ___________. A new primitive can be made by defining a procedure.", "primitives", "language", "computer", "complex", null },
                { "The words used as LOGO commands are called primitives. A new primitive can be made by defining a ________.", "procedure", "language", "computer", "complex", null },
                { "The ___________ command is used to change the colour of the line drawn by the pen.", "SETPC", "FILL", "SETSC", "SETfC", null },
                { "The ___________ command is used to fill colour in a closed area.", "FILL", "SETSC", "SETPC", "SETfC", null },
        });

        // Chapter 9:
        FIXED_QUESTIONS.put(9, new String[][]{
                { "The command PR RANDOM 100 will pick out a random number:", "Between 0 and 99", "Between 0 and 100", "Between 1 and 100", "Between 1 and 99", null },
                { /*9101*/ "With the turtle at the home position, which one of the program, given in the box below, will draw a square:", "LOGO Program 2", "LOGO Program 1", "LOGO Program 3", "LOGO Program 4", "LOGO Program 1:\n==============\nFD 100\nRT 90\nFD 50\nRT 90\nFD 100\nRT 90\nFD 50\n\nLOGO Program 2:\n==============\nFD 100\nRT 90\nFD 100\nRT 90\nFD 100\nRT 90\nFD 100\n\nLOGO Program 3:\n==============\nFD 100\nRT 90\nFD 100\nRT 90\nFD 120\nRT 90\nFD 100\n\nLOGO Program 4:\n==============\nFD 100\nRT 90\nFD 100\nRT 90\nFD 100", null },
                { /*9102*/ "What shape will you get if you run the commands given in the box below?", "Rectangle", "Circle", "Square", "Vertical line", "FD 100\nRT 90\nFD 50\nRT 90\nFD 100\nRT 90\nFD 50", null },
                { "Where does the command FPUT insert a new item in a list?", "Before the list", "After the list", "In a random position within the list", "In the middle of the list", null },
                { "Which of these are input commands?", "All of these", "RL", "RW", "RC", null },
                { "Which of these commands is given to check a condition?", "IFELSE", "MAKE", "PR", "BUTFIRST", null },
                { "What is the output of the LOGO command: PRINT 3 * 4", "12", "34", "3.4", "3 * 4", null },
                { "What is the output of the LOGO command: PRINT \"3 * 4\"", "3 * 4", "12", "34", "3.4", null },
                { "Which one of the following could be the output of the LOGO command: PR RANDOM 100", "45", "1000", "110", "101", null },
                { "What is the output of the LOGO command: PR BUTFIRST [1 2 3 4]", "2 3 4", "1", "3", "4", null },
                { "What is the output of the LOGO command: PR FIRST : BIRDS", "Displays the first item on the list of BIRDS", "B", "IRDS", "Displays all the items on the list of BIRDS", null },
                { "What is the output of the LOGO command: PRINT FPUT \"sweet [mango]", "sweet mango", "mango sweet", "s mango", "FPUT sweet mango", null },
                { "What is the output of the LOGO command: PRINT LPUT \"sweet [mango]", "mango sweet", "sweet mango", "s mango", "FPUT sweet mango", null },
                { "Which input command enables you to enter a list of words?", "RL", "READWORD", "READCHAR", "RC", null },
                { "Which input command will you use to enter a single character?", "READCHAR", "RL", "READWORD", "PR", null },
                { "Which input command will you use to enter a three-digit number?", "READWORD", "RL", "READCHAR", "PR", null },
                //{ "Biman, Sunil and Vinod were asked to write Logo programs to draw a square. The Logo program written by them is  shown in the box below. Find out whose program is correct.", "Sunil's program is correct", "Biman's program is correct", "Vinod's program is correct", "All programs are correct", "Program written by Biman:\n========================\nFD 100\nRT 90\nFD 50\nRT 90\nFD 100\nRT 90\nFD 50\n\nProgram written by Sunil:\n========================\nFD 100\nRT 90\nFD 100\nRT 90\nFD 100\nRT 90\nFD 100\n\nProgram written by Vinod:\n========================\nFD 100\nRT 90\nFD 100\nRT 90\nFD 120\nRT 90\nFD 100", null}
                {/*9201*/ "%1$s, %2$s and %3$s were asked to write LOGO programs to draw a square. The LOGO program written by them is  shown in the box below. Find out whose program is correct.", "%2$s's program is correct", "%1$s's program is correct", "%3$s's program is correct", "All programs are correct", "Program written by %1$s:\n========================\nFD 100\nRT 90\nFD 50\nRT 90\nFD 100\nRT 90\nFD 50\n\nProgram written by %2$s:\n========================\nFD 100\nRT 90\nFD 100\nRT 90\nFD 100\nRT 90\nFD 100\n\nProgram written by %3$s:\n========================\nFD 100\nRT 90\nFD 100\nRT 90\nFD 120\nRT 90\nFD 100", null}
        });

        // Chapter 10:
        FIXED_QUESTIONS.put(10, new String[][]{
                { "TRUE or FALSE. Animation and game are same thing", "FALSE", "TRUE", "", "", null },
                { "TRUE or FALSE. In a game the player has control over the outcome", "TRUE", "FALSE", "", "", null },
                { "TRUE or FALSE. The result of a game is not known in advance and depends on the player's actions", "TRUE", "FALSE", "", "", null },
        });

        // Chapter 11:
        FIXED_QUESTIONS.put(11, new String[][]{
                { "To which part of the main screen are the command blocks dragged to build the program?", "Scripts area", "Control panel", "Upper panel on the stage", "Lower panel on the stage", null },
                { "Which of these commands are not present on the top level menu?", "Fill", "File", "Edit", "Share", null },
                { "In which category is the 'touching colour' block present?", "Sensing", "Motion", "Control", "Operators", null },
                { "To 'pick random' block is present in the category:", "Operators", "Motion", "Control", "Sensing", null },
                { "Scratch programs are called __________", "projects", "instructions", "games", "videos", null },
                { "In Scratch, commands are also called __________", "blocks", "glide", "sprite", "costumes", null },
                { "A sprite may have many __________", "costumes", "video", "games", "project", null },
                { "You can reduce the size of a sprite by using the __________ button", "Shrink", "Small", "Reduce", "Decrease", null },
                { "To make the gliding speed slower you have to _______ the time to reach the goal", "increase", "decrease", "", "", null },
                { "A position on the stage area is defined by a ______ value and a Y value", "X", "Z", "A", "B", null },
        });

        // Chapter 12:
        FIXED_QUESTIONS.put(12, new String[][]{
                { "The number of computers connected to the Internet are:", "few millions", "few hundreds", "few thousands", "few billions", "", null },
                { "Which of these is not a search engine?", "pics4learning.com", "google.in", "yahoo.in", "safesearchkids.com", "", null },
                { "TRUE or FALSE. Hyperlinks connect you to other web pages", "TRUE", "FALSE", "", "", "", null },
                { "TRUE or FALSE. Information available on a website does not change", "FALSE", "TRUE", "", "", "", null },
                { "TRUE or FALSE. Google is an example of search engine", "TRUE", "FALSE", "", "", "", null },
                { "TRUE or FALSE. Search engines help us to search information when we do not know the exact URL of the relevant websites", "TRUE", "FALSE", "", "", "", null },
                { "TRUE or FALSE. Google Docs helps us to send mails", "FALSE", "TRUE", "", "", "", null },
                { "Most websites are divided into a number of _______", "web pages", "none of these", "websites", "home pages", "", null },
                { "Links which connect you to other web pages are known as ______", "hyperlinks", "websites", "home pages", "web pages", "", null },
                { "The act of searching for information over the Net is known as ________", "web browsing", "clicking hyperlinks", "playing games on the net", "home pages", "", null },
                { "Mozilla firefox is an example of ______", "web browser", "system software", "home pages", "web pages", "", null },
                { "Google Docs is a ______ tool", "web sharing", "websites", "home pages", "web pages", "", null },
                { "Internet Explorer is an example of ______", "web browser", "system software", "home pages", "web pages", "", null },
                { "Google Chrome is an example of ______", "web browser", "system software", "home pages", "web pages", "", null },
                { "Each website has a main page known as the __________", "Home page", "google", "web browser", "hyperlink", "", null },
                { "TRUE or FALSE. When the mouse pointer comes to a hyperlink, it changes into a hand.", "TRUE", "FALSE", "", "", "", null },
                { "TRUE or FALSE. The Internet is a huge network of several billion computers all over the world.", "TRUE", "FALSE", "", "", "", null },
                { "TRUE or FALSE. Internet Explorer is the only web browser available.", "FALSE", "TRUE", "", "", "", null },
                { "TRUE or FALSE. Google chrome is a web browser.", "TRUE", "FALSE", "", "", "", null },
                { "TRUE or FALSE. Mozilla firebox is a web browser.", "TRUE", "FALSE", "", "", "", null },
                { "TRUE or FALSE. MS LOGO is a web browser.", "FALSE", "TRUE", "", "", "", null },
                { "URL stands for:", "Uniform Resource Locator", "Uniform Resource Limited", "", "", "", null },
                { "TRUE or FALSE. google.co.in is a search engine", "TRUE", "FALSE", "", "", "", null },
                { "TRUE or FALSE. Dropbox can be used to share documents over the Internet", "TRUE", "FALSE", "", "", "", null },
                { "TRUE or FALSE. Dropbox is a document sharing application over the Internet", "TRUE", "FALSE", "", "", "", null },
                { "The unique address of a particular website is known as _______", "URL", "hyperlink", "", "", "", null },
                { "The main page of a website is called the:", "home page", "web page", "hyperlink", "linked page", "", null },
                { "Which of these can you search for on the Internet using a search engine?", "All of these", "Information", "Pictures", "Videos", "", null },
                { "Which of the following is not true about the Internet", "Information available on the Internet is always accurate", "Information available on the Internet changes continuously", "A search with the same keywords will give different websites if done after a few days", "Internet network also carries programs that can damage your computer", "", null },
                { "The huge network of computers all over the world is called ______", "Internet", "Internet browser", "Home page", "Web page", "", null },
                { "You can click on a ________ on a web page to find more information on the topic", "hyperlink", "Internet browser", "Home page", "Web page", "", null },
                { "For surfing the Net the software you need is called a web ________", "browser", "Internet", "Home page", "Web page", "", null },
                { "The software used to search for information on the Internet is called a ____________", "search engine", "web browser", "Home page", "Web page", "", null },
                { "You can _________ a site that you would like to visit again", "bookmark", "search engine", "web browser", "Web page", "", null },
                { "Most websites are divided into web _____", "pages", "search engine", "web browser", "bookmark", "", null },
        });
    }

    public static String[][] getFixedQuestions(int chapter)
    {
        return FIXED_QUESTIONS.getOrDefault(chapter, new String[0][]);
    }
}